version: '3.2'
services:
  twig:
    image: serdmanczyk/twig
    networks:
      - reverseproxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=twig"
      - "traefik.frontend.rule=Host:twig.erdmanczyk.com"
      - "traefik.docker.network=reverseproxy_reverseproxy"
    build: 
      context: .

networks:
  reverseproxy:
    external:
      name: reverseproxy_reverseproxy
